import React from 'react'
import { useRouter } from "next/router";
import Head from 'next/head'

const Project = ({mydata}) => {
   const router = useRouter();
   console.log(mydata.items)
   //const {full_name} = mydata.items
  return (
    <div>
        <Head>
            <title>akaushik509-portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div style={{  padding:"10px",backgroundColor:"#2D3748", width:"80%", margin:"auto" , marginTop:"10px", borderRadius:"10px"}}>
                <center><h1>Projects</h1></center>
                <div style={{display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:"100px"}}>
                    {
                        mydata.items.map((item)=>(
                            <div key={item.id}>
                                <h1 onClick={()=>window.location=item.html_url}>{item.full_name}</h1>
                                <div style={{display:"flex", justifyContent:"space-between"}}>
                                  <div style={{display:"flex",width:"50%", gap:"20px"}}>
                                    <p>Star Count = {item.stargazers_count}</p>
                                    <p>Forks Count = {item.forks_count}</p>
                                  </div>
                                  <div style={{display:"flex",width:"50%"}}>
                                    <p>Language = {item.language}</p>
                                  </div>
                                </div>
                            </div>
                        ))
                    }
                </div>
            </div>
        </main>
    </div>
  )
}

export async function getServerSideProps(){
    let res = await fetch("https://api.github.com/search/repositories?q=user:akaushik509+fork:true&sort=updated&per_page=10&type=Repositories");
    let data = await res.json();
    return {
      props:{
        mydata:data,
      }
    }
  }

export default Project

/* GET https://api.github.com/search/repositories?q=user:${username}+fork:true&sort=updated&per_page=10&type=Repositories */

/* GET https://api.github.com/users/${username} */